-- Clear existing data
DELETE FROM "_BlockVariantToTag";
DELETE FROM "BlockVariant";
DELETE FROM "Tag";
DELETE FROM "_ProjectToTag";

-- Landing Page Tags
INSERT INTO "Tag" (id, name, category, "projectType", "createdAt", "updatedAt") VALUES
-- Industry tags for landing pages
('tag-tech-landing', 'Technology', 'industry', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tag-finance-landing', 'Finance', 'industry', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tag-health-landing', 'Healthcare', 'industry', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tag-education-landing', 'Education', 'industry', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tag-retail-landing', 'Retail', 'industry', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Purpose tags for landing pages
('tag-product-landing', 'Product Launch', 'purpose', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tag-service-landing', 'Service Showcase', 'purpose', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tag-lead-landing', 'Lead Generation', 'purpose', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tag-event-landing', 'Event Registration', 'purpose', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Style tags for landing pages
('tag-modern-landing', 'Modern', 'style', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tag-minimal-landing', 'Minimal', 'style', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('tag-bold-landing', 'Bold', 'style', 'landing', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Block Variants for Landing Pages
INSERT INTO "BlockVariant" (id, name, type, content) VALUES
-- Technology Headers
('header-tech-1', 'Technology Modern Header', 'header', E'<header class="bg-gradient-to-r from-purple-600 to-blue-600 text-white">\n  <nav class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">\n    <div class="flex justify-between items-center">\n      <div class="flex items-center">\n        <span class="text-2xl font-bold">TechSolutions</span>\n      </div>\n      <div class="hidden md:block">\n        <div class="ml-10 flex items-baseline space-x-4">\n          <a href="#" class="text-white hover:text-blue-100 px-3 py-2 rounded-md text-sm font-medium">Products</a>\n          <a href="#" class="text-white hover:text-blue-100 px-3 py-2 rounded-md text-sm font-medium">Solutions</a>\n          <a href="#" class="text-white hover:text-blue-100 px-3 py-2 rounded-md text-sm font-medium">Documentation</a>\n          <a href="#" class="bg-blue-500 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-blue-400">Get Started</a>\n        </div>\n      </div>\n    </div>\n  </nav>\n</header>'),

-- Technology Content Blocks
('content-tech-1', 'Technology Features Grid', 'feature', E'<section class="py-20 bg-white">\n  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">\n    <div class="text-center mb-16">\n      <h2 class="text-4xl font-bold text-gray-900">Cutting-Edge Technology Solutions</h2>\n      <p class="mt-4 text-xl text-gray-600">Empowering businesses with innovative technology</p>\n    </div>\n    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">\n      <div class="bg-purple-50 p-8 rounded-xl">\n        <div class="w-12 h-12 bg-purple-100 rounded-xl flex items-center justify-center mb-6">\n          <svg class="w-6 h-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">\n            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />\n          </svg>\n        </div>\n        <h3 class="text-xl font-semibold mb-4">Advanced Analytics</h3>\n        <p class="text-gray-600">Powerful insights with AI-driven analytics</p>\n      </div>\n      <div class="bg-blue-50 p-8 rounded-xl">\n        <div class="w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center mb-6">\n          <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">\n            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 11c0 3.517-1.009 6.799-2.753 9.571m-3.44-2.04l.054-.09A13.916 13.916 0 008 11a4 4 0 118 0c0 1.017-.07 2.019-.203 3m-2.118 6.844A21.88 21.88 0 0015.171 17m3.839 1.132c.645-2.266.99-4.659.99-7.132A8 8 0 008 4.07M3 15.364c.64-1.319 1-2.8 1-4.364 0-1.457.39-2.823 1.07-4" />\n          </svg>\n        </div>\n        <h3 class="text-xl font-semibold mb-4">Cloud Solutions</h3>\n        <p class="text-gray-600">Scalable and secure cloud infrastructure</p>\n      </div>\n      <div class="bg-indigo-50 p-8 rounded-xl">\n        <div class="w-12 h-12 bg-indigo-100 rounded-xl flex items-center justify-center mb-6">\n          <svg class="w-6 h-6 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">\n            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />\n          </svg>\n        </div>\n        <h3 class="text-xl font-semibold mb-4">Enterprise Security</h3>\n        <p class="text-gray-600">Advanced security for your business</p>\n      </div>\n    </div>\n  </div>\n</section>'),

('content-tech-2', 'Technology Statistics', 'content', E'<section class="py-20 bg-gray-50">\n  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">\n    <div class="grid grid-cols-1 md:grid-cols-4 gap-8 text-center">\n      <div>\n        <div class="text-4xl font-bold text-purple-600 mb-2">99.9%</div>\n        <div class="text-gray-600">Uptime SLA</div>\n      </div>\n      <div>\n        <div class="text-4xl font-bold text-purple-600 mb-2">1000+</div>\n        <div class="text-gray-600">Enterprise Clients</div>\n      </div>\n      <div>\n        <div class="text-4xl font-bold text-purple-600 mb-2">24/7</div>\n        <div class="text-gray-600">Support</div>\n      </div>\n      <div>\n        <div class="text-4xl font-bold text-purple-600 mb-2">50+</div>\n        <div class="text-gray-600">Countries</div>\n      </div>\n    </div>\n  </div>\n</section>'),

('cta-tech-1', 'Technology CTA', 'cta', E'<section class="py-20 bg-gradient-to-r from-purple-600 to-blue-600">\n  <div class="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">\n    <h2 class="text-3xl font-bold text-white mb-8">Ready to Transform Your Business?</h2>\n    <p class="text-xl text-blue-100 mb-8">Join thousands of companies already using our solutions</p>\n    <div class="flex flex-col sm:flex-row gap-4 justify-center">\n      <button class="px-8 py-4 bg-white text-purple-600 rounded-lg font-semibold hover:bg-gray-50 transition-colors">\n        Start Free Trial\n      </button>\n      <button class="px-8 py-4 bg-blue-500 text-white rounded-lg font-semibold hover:bg-blue-400 transition-colors">\n        Schedule Demo\n      </button>\n    </div>\n  </div>\n</section>'),

('footer-tech-1', 'Technology Footer', 'footer', E'<footer class="bg-gray-900 text-gray-300 py-12">\n  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">\n    <div class="grid grid-cols-1 md:grid-cols-4 gap-8">\n      <div>\n        <h3 class="text-lg font-semibold text-white mb-4">TechSolutions</h3>\n        <p class="text-sm">Empowering businesses with innovative technology solutions.</p>\n      </div>\n      <div>\n        <h4 class="text-sm font-semibold text-white mb-4">Products</h4>\n        <ul class="space-y-2 text-sm">\n          <li><a href="#" class="hover:text-white">Analytics Platform</a></li>\n          <li><a href="#" class="hover:text-white">Cloud Services</a></li>\n          <li><a href="#" class="hover:text-white">Security Suite</a></li>\n        </ul>\n      </div>\n      <div>\n        <h4 class="text-sm font-semibold text-white mb-4">Resources</h4>\n        <ul class="space-y-2 text-sm">\n          <li><a href="#" class="hover:text-white">Documentation</a></li>\n          <li><a href="#" class="hover:text-white">API Reference</a></li>\n          <li><a href="#" class="hover:text-white">Blog</a></li>\n        </ul>\n      </div>\n      <div>\n        <h4 class="text-sm font-semibold text-white mb-4">Company</h4>\n        <ul class="space-y-2 text-sm">\n          <li><a href="#" class="hover:text-white">About</a></li>\n          <li><a href="#" class="hover:text-white">Careers</a></li>\n          <li><a href="#" class="hover:text-white">Contact</a></li>\n        </ul>\n      </div>\n    </div>\n    <div class="border-t border-gray-800 mt-8 pt-8 text-sm text-center">\n      <p>&copy; 2024 TechSolutions. All rights reserved.</p>\n    </div>\n  </div>\n</footer>'),

-- Education Headers
('header-education-1', 'Education Modern Header', 'header', E'<header class="bg-blue-600 text-white">\n  <nav class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">\n    <div class="flex justify-between items-center">\n      <div class="flex items-center">\n        <span class="text-2xl font-bold">EduPlatform</span>\n      </div>\n      <div class="hidden md:block">\n        <div class="ml-10 flex items-baseline space-x-4">\n          <a href="#" class="text-white hover:text-blue-100 px-3 py-2 rounded-md text-sm font-medium">Courses</a>\n          <a href="#" class="text-white hover:text-blue-100 px-3 py-2 rounded-md text-sm font-medium">Programs</a>\n          <a href="#" class="text-white hover:text-blue-100 px-3 py-2 rounded-md text-sm font-medium">Resources</a>\n          <a href="#" class="bg-blue-500 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-blue-400">Get Started</a>\n        </div>\n      </div>\n    </div>\n  </nav>\n</header>'),

-- Education Content Blocks
('content-education-1', 'Education Features Grid', 'feature', E'<section class="py-20 bg-white">\n  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">\n    <div class="text-center mb-16">\n      <h2 class="text-4xl font-bold text-gray-900">Transform Your Learning Journey</h2>\n      <p class="mt-4 text-xl text-gray-600">Discover a new way of learning with our innovative platform</p>\n    </div>\n    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">\n      <div class="bg-blue-50 p-8 rounded-xl">\n        <div class="w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center mb-6">\n          <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">\n            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />\n          </svg>\n        </div>\n        <h3 class="text-xl font-semibold mb-4">Expert-Led Courses</h3>\n        <p class="text-gray-600">Learn from industry professionals and experienced educators</p>\n      </div>\n      <div class="bg-blue-50 p-8 rounded-xl">\n        <div class="w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center mb-6">\n          <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">\n            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 15l-2 5L9 9l11 4-5 2zm0 0l5 5M7.188 2.239l.777 2.897M5.136 7.965l-2.898-.777M13.95 4.05l-2.122 2.122m-5.657 5.656l-2.12 2.122" />\n          </svg>\n        </div>\n        <h3 class="text-xl font-semibold mb-4">Interactive Learning</h3>\n        <p class="text-gray-600">Engage with content through quizzes, projects, and live sessions</p>\n      </div>\n      <div class="bg-blue-50 p-8 rounded-xl">\n        <div class="w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center mb-6">\n          <svg class="w-6 h-6 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">\n            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />\n          </svg>\n        </div>\n        <h3 class="text-xl font-semibold mb-4">Verified Certificates</h3>\n        <p class="text-gray-600">Earn recognized certificates upon course completion</p>\n      </div>\n    </div>\n  </div>\n</section>'),

('content-education-2', 'Education Statistics', 'content', E'<section class="py-20 bg-gray-50">\n  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">\n    <div class="grid grid-cols-1 md:grid-cols-4 gap-8 text-center">\n      <div>\n        <div class="text-4xl font-bold text-blue-600 mb-2">10K+</div>\n        <div class="text-gray-600">Active Students</div>\n      </div>\n      <div>\n        <div class="text-4xl font-bold text-blue-600 mb-2">500+</div>\n        <div class="text-gray-600">Expert Instructors</div>\n      </div>\n      <div>\n        <div class="text-4xl font-bold text-blue-600 mb-2">1000+</div>\n        <div class="text-gray-600">Online Courses</div>\n      </div>\n      <div>\n        <div class="text-4xl font-bold text-blue-600 mb-2">95%</div>\n        <div class="text-gray-600">Success Rate</div>\n      </div>\n    </div>\n  </div>\n</section>'),

('cta-education-1', 'Education CTA', 'cta', E'<section class="py-20 bg-blue-600">\n  <div class="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">\n    <h2 class="text-3xl font-bold text-white mb-8">Start Your Learning Journey Today</h2>\n    <p class="text-xl text-blue-100 mb-8">Join thousands of students already learning on our platform</p>\n    <div class="flex flex-col sm:flex-row gap-4 justify-center">\n      <button class="px-8 py-4 bg-white text-blue-600 rounded-lg font-semibold hover:bg-blue-50 transition-colors">\n        Browse Courses\n      </button>\n      <button class="px-8 py-4 bg-blue-500 text-white rounded-lg font-semibold hover:bg-blue-400 transition-colors">\n        Start Free Trial\n      </button>\n    </div>\n  </div>\n</section>'),

('footer-education-1', 'Education Footer', 'footer', E'<footer class="bg-gray-900 text-gray-300 py-12">\n  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">\n    <div class="grid grid-cols-1 md:grid-cols-4 gap-8">\n      <div>\n        <h3 class="text-lg font-semibold text-white mb-4">EduPlatform</h3>\n        <p class="text-sm">Empowering learners worldwide with quality education.</p>\n      </div>\n      <div>\n        <h4 class="text-sm font-semibold text-white mb-4">Programs</h4>\n        <ul class="space-y-2 text-sm">\n          <li><a href="#" class="hover:text-white">Certificate Courses</a></li>\n          <li><a href="#" class="hover:text-white">Degree Programs</a></li>\n          <li><a href="#" class="hover:text-white">Professional Training</a></li>\n        </ul>\n      </div>\n      <div>\n        <h4 class="text-sm font-semibold text-white mb-4">Resources</h4>\n        <ul class="space-y-2 text-sm">\n          <li><a href="#" class="hover:text-white">Learning Path</a></li>\n          <li><a href="#" class="hover:text-white">Success Stories</a></li>\n          <li><a href="#" class="hover:text-white">Blog</a></li>\n        </ul>\n      </div>\n      <div>\n        <h4 class="text-sm font-semibold text-white mb-4">Contact</h4>\n        <ul class="space-y-2 text-sm">\n          <li><a href="#" class="hover:text-white">Support</a></li>\n          <li><a href="#" class="hover:text-white">Careers</a></li>\n          <li><a href="#" class="hover:text-white">Partners</a></li>\n        </ul>\n      </div>\n    </div>\n    <div class="border-t border-gray-800 mt-8 pt-8 text-sm text-center">\n      <p>&copy; 2024 EduPlatform. All rights reserved.</p>\n    </div>\n  </div>\n</footer>');

-- Link block variants with tags
INSERT INTO "_BlockVariantToTag" ("A", "B") VALUES
-- Technology blocks
('header-tech-1', 'tag-tech-landing'),
('content-tech-1', 'tag-tech-landing'),
('content-tech-2', 'tag-tech-landing'),
('cta-tech-1', 'tag-tech-landing'),
('footer-tech-1', 'tag-tech-landing'),

-- Education blocks
('header-education-1', 'tag-education-landing'),
('content-education-1', 'tag-education-landing'),
('content-education-2', 'tag-education-landing'),
('cta-education-1', 'tag-education-landing'),
('footer-education-1', 'tag-education-landing');